set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Jellyfin")
set(CPACK_PACKAGE_VENDOR "Jellyfin")
set(CPACK_PACKAGE_NAME "Jellyfin")
string(REPLACE "." ";" VERSION_PARTS "${VERSION_BASE}")
list(GET VERSION_PARTS 0 CPACK_PACKAGE_VERSION_MAJOR)
list(GET VERSION_PARTS 1 CPACK_PACKAGE_VERSION_MINOR)
list(GET VERSION_PARTS 2 CPACK_PACKAGE_VERSION_PATCH)

set(CPACK_SYSTEM_NAME "macosx-arm64")
set(CPACK_PACKAGE_FILE_NAME "Jellyfin-${VERSION_STRING}-${CPACK_SYSTEM_NAME}")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "Jellyfin-${VERSION_STRING}-src")

set(CPACK_PACKAGE_INSTALL_DIRECTORY "Jellyfin")
set(CPACK_STRIP_FILES 1)


set(CPACK_GENERATOR "ZIP")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 0)
configure_file(${CMAKE_SOURCE_DIR}/CMakeModules/CPackGeneratedConfig.cmake.in ${CMAKE_BINARY_DIR}/CPackGeneratedConfig.cmake)
set(CPACK_PROJECT_CONFIG_FILE ${CMAKE_BINARY_DIR}/CPackGeneratedConfig.cmake)

include(CPack)
cpack_add_component(Core DISPLAY_NAME "Jellyfin" DESCRIPTION "Jellyfin (Core Application)" REQUIRED)