message(STATUS ${CMAKE_FIND_ROOT_PATH})
OPTION(ENABLE_SDL2 "Enable SDL2 for joystick handling" ON)
if(ENABLE_SDL2)
  find_package(SDL2)
  if(SDL2_FOUND)
    find_package(Iconv REQUIRED)
    find_library(FORCEFEEDBACK ForceFeedback)
    find_library(CARBON Carbon)
    find_library(COREAUDIO CoreAudio)
    find_library(COREVIDEO CoreVideo)
    find_library(AUDIOUNIT AudioUnit)
    list(APPEND SDL2_LIBRARY ${FORCEFEEDBACK} ${CARBON} ${COREAUDIO} ${AUDIOUNIT} ${COREVIDEO} ${ICONV_LIBRARIES})
  endif(SDL2_FOUND)
  if(SDL2_FOUND)
    list(APPEND ENABLED_INPUTS SDL2)
    add_definitions(-DHAVE_SDL)
    include_directories(${SDL2_INCLUDE_DIR})
    set(EXTRA_LIBS ${SDL2_LIBRARY})
  endif(SDL2_FOUND)

endif(ENABLE_SDL2)

list(APPEND ENABLED_INPUTS "AppleRemote")

string(REPLACE ";" " " _STR "${ENABLED_INPUTS}")
message(STATUS "Enabled Inputs: " ${_STR})
